# Generated by Django 5.0.6 on 2024-05-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_networktraffic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networktraffic',
            options={'ordering': ('-created_at',), 'verbose_name': 'Network Traffic', 'verbose_name_plural': 'Network Traffic'},
        ),
    ]
